-----------theme-----------
require('config/catppuccin')
----------general----------
require('config/lualine')
require('config/bufferline')
require('config/toggleterm')
require('config/harpoon')
require('config/mini')
require('config/alpha')
require('config/diffview')
require('config/telescope')
--------lsp & text---------
require('config/treesitter')
require('config/lsp')
require('config/fidget')
require('config/cmp')
require('config/dap')
require('config/nvim-dap-ui')
require('config/dap-virtual-text')
