-----------theme-----------
-- require('config/onedark')
-- require('config/gruvbox')
require('config/catppuccin')
----------general----------
require('config/lualine')
require('config/bufferline')
require('config/nvim-comment')
require('config/toggleterm')
require('config/harpoon')
-- require('config/nvim-autopairs')
require('config/mini')
require('config/alpha')
require('oil').setup()
-- require('config/which-key')
require('config/diffview')
require('config/telescope')
--------lsp & text---------
-- require('config/treesitter')
require('config/lsp')
require('config/cmp')
require('config/dap')
require('config/nvim-dap-ui')
require('config/dap-virtual-text')
require('config/fidget')
-- require('config/rainbow-delimiters')
