# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#color-attributes
git:
  paging:
    colorArg: always
    pager: delta --dark --side-by-side --paging=never
gui:
  theme:
    selectedLineBgColor:
      - default
      - reverse
    selectedRangeBgColor:
      - default
      - reverse

