require('configs/onedark') -- has to be loaded first
require('configs/lualine')
require('configs/bufferline')
require('configs/nvim-comment')
-- require('configs/nvim-tree') -- *****************TODO remove this if the telescope file browser works well **********************
require('configs/toggleterm')
require('configs/treesitter')
require('configs/cmp')
require('configs/indent-blankline')
require('configs/telescope')
require('configs/gitsigns')
require('configs/mason') --needs to come before lspconfig
require('configs/lspconfig')
require('configs/project')
require('configs/diffview')
require('configs/fidget')
require('configs/nvim-autopairs')
require('configs/mini')
require('configs/alpha')
require('configs/illuminate')
