-----------theme-----------
-- require('configs/onedark')
-- require('configs/gruvbox')
require('configs/catppuccin')
----------general----------
require('configs/lualine')
require('configs/bufferline')
require('configs/nvim-comment')
require('configs/toggleterm')
require('configs/nvim-autopairs')
require('configs/mini')
require('configs/alpha')
-- require('configs/which-key')
require('configs/diffview')
require('configs/telescope')
--------lsp & text---------
require('configs/lsp')
require('configs/cmp')
require('configs/fidget')
require('configs/treesitter')
require('configs/rainbow-delimiters')
