#
# you really gotta
# (prompt)$ tmux source-file /path/to/config.conf 
# to make changes...
#
set -g default-shell $SHELL

# enable terminal colors
set-option -sa terminal-overrides ",xterm*:Tc"


############## tmux-sensible ##############
# enable mouse
set -g mouse on
# Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 0
# Increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 50000
# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000
# Refresh 'status-left' and 'status-right' more often, from every 15s to 5s
set -g status-interval 5
# Emacs key bindings in tmux command prompt (prefix + :) are better than
# vi keys, even for vim users
set -g status-keys emacs
# Focus events enabled for terminals that support them
set -g focus-events on
# Super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on
# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on


############## keybinds ##############
# rebind command prefix key
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

####### sessions
# new session
bind s command-prompt -p "New Session:" "new-session -A -s '%%'"

####### windows
bind w new-window # window at home dir
bind c new-window -c "#{pane_current_path}" # window at current path
bind t run-shell "tmux neww ~/scripts/tmux-sessionizer.sh" 

# this may conflict with things i want to setup in nvim later
# -n is means without prefix key
bind -n M-h previous-window 
bind -n M-l next-window

####### panes
# create new panes
bind \\ split-window -h
bind - split-window -v

# focesed pane zoom
bind m resize-pane -Z


############## theme ##############
run ~/.config/tmux/plugins/tmux/catppuccin.tmux
